mutation StopElection($electionId: ID!) {
  stopElection(input: { electionId: $electionId }) {
    election {
      id
      name
      description
      candidates {
        id
        name
        description
      }
      status
      statusTransitions {
        on
        status
      }
      results {
        winner {
          id
          name
        }
      }
    }
  }
}
